-- MySQL Script generated by MySQL Workbench
-- Qui 04 Mai 2017 16:55:04 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sysprints3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sysprints3` ;

-- -----------------------------------------------------
-- Schema sysprints3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysprints3` DEFAULT CHARACTER SET utf8 ;
USE `sysprints3` ;

-- -----------------------------------------------------
-- Table `sysprints3`.`printers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprints3`.`printers` ;

CREATE TABLE IF NOT EXISTS `sysprints3`.`printers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `allow` TINYINT(1) NULL,
  `name` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NULL,
  `month_count` INT NULL DEFAULT 0,
  `quota_period` INT NULL DEFAULT 0,
  `page_limite` INT NULL DEFAULT 0,
  `k_limit` INT NULL DEFAULT 0,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysprints3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprints3`.`users` ;

CREATE TABLE IF NOT EXISTS `sysprints3`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  `adress` VARCHAR(455) NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `quota` INT NULL DEFAULT 0,
  `month_count` INT NULL,
  `thumbnailphoto` TEXT NULL,
  `job_count` INT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysprints3`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprints3`.`jobs` ;

CREATE TABLE IF NOT EXISTS `sysprints3`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `printer_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `pages` INT NOT NULL,
  `copies` INT NULL DEFAULT 0,
  `host` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `params` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_users_idx` (`user_id` ASC),
  INDEX `fk_jobs_prints1_idx` (`printer_id` ASC),
  CONSTRAINT `fk_jobs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `sysprints3`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jobs_prints1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `sysprints3`.`printers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysprints3`.`users_printers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprints3`.`users_printers` ;

CREATE TABLE IF NOT EXISTS `sysprints3`.`users_printers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `printer_id` INT NOT NULL,
  INDEX `fk_users_has_printers_printers1_idx` (`printer_id` ASC),
  INDEX `fk_users_has_printers_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_printers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sysprints3`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_printers_printers1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `sysprints3`.`printers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysprints3`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sysprints3`.`settings` ;

CREATE TABLE IF NOT EXISTS `sysprints3`.`settings` (
  `id` INT NOT NULL,
  `app_status` TINYINT(1) NULL,
  `app_debug` TINYINT(1) NULL,
  `app_title` VARCHAR(45) NULL,
  `app_locale` VARCHAR(45) NULL,
  `app_dateformtar` VARCHAR(45) NULL,
  `app_https` TINYINT(1) NULL,
  `app_auth` TINYINT(1) NULL,
  `ad_conect` TINYINT(1) NULL DEFAULT 0,
  `ad_host` VARCHAR(455) NULL,
  `ad_port` INT NULL DEFAULT 389,
  `ad_dn` VARCHAR(455) NULL,
  `ad_user` VARCHAR(45) NULL,
  `ad_pass` VARCHAR(455) NULL,
  `ad_suffix` VARCHAR(455) NULL,
  `ad_attr` VARCHAR(455) NULL,
  `ad_filter` VARCHAR(455) NULL,
  `mail_conect` TINYINT(1) NULL,
  `mail_transport` VARCHAR(45) NULL DEFAULT 'Smtp',
  `mail_title` VARCHAR(45) NULL,
  `mail_from` VARCHAR(455) NULL,
  `mail_host` VARCHAR(100) NULL,
  `mail_port` INT NULL DEFAULT 465,
  `mail_timeout` INT NULL DEFAULT 30,
  `mail_username` VARCHAR(100) NULL,
  `mail_password` VARCHAR(455) NULL,
  `mail_charset` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
