#!/bin/bash

case "$1" in
	'user')
		whoami
		;;
	'printer')
		php /opt/lampp/htdocs/cakephp/sysprint-3.6/bin/cake.php prints.printer
		;;
	'lpadmin')
		$($@)
		;;
	'getLpPrinters')
		sudo cat /etc/cups/printers.conf | grep "<Printer \|<DefaultPrinter " | sed 's/<Printer \|<DefaultPrinter //' | sed 's/>//'
esac
