#!/bin/bash

function_exists() {
    declare -f -F $1 > /dev/null
    return $?
}

function getUser(){
	whoami
}

function getPrinter(){
	php ../../../../bin/cake.php prints.printer quota;
}

function getPrinters(){
	[ -e $2 ] &&
	sudo cat $2 | grep "<Printer \|<DefaultPrinter " | sed 's/<Printer \|<DefaultPrinter //' | sed 's/>//'
}

function getUser(){
	whoami
}

function readLogs(){
	sudo cat $2 | sed '/^$/d' ;
}

function setLpadmin(){
	cd $(dirname ${BASH_SOURCE[0]});
	php ../../../../bin/cake.php prints.printer quota;
}

function_exists $1 && $1 $* ||  return false;
